import React, { Component } from "react";
import Link from 'next/link'
// upper-latin
const Blog21 = () => {
    return (
        <React.Fragment>

<div class="main-content">
{/* <!--======= Blog =======--> */}
<div className="h1 compare-title col-lg-12" style={{backgroundColor: '#146cae', margin: '0px', padding: '0px', textAlign: 'center', marginBottom: '60px', width: '100%', height: '90px', display: 'flex', alignItems: 'center', textAlign: 'center'}}><span style={{color: 'white', fontSize: '1.8rem', margin: 'auto', fontWeight: '600'}}>Términos y condiciones (General)</span></div>
    <section class="">
        <div class="container">
            <div class="row">
                <div class="col-md-12 col-sm-12">
                    <div>
                        <div class="iq-blog-detail">
                            {/* <div class="blog-title"> <a href="blog-single.html"><h5 class="iq-tw-6 iq-mb-10">Blogpost With Image</h5></a></div> */}
                            <div class="blog-content">

                                                        
                            <ol>
                            <p style={{textAlign: 'justify', marginBottom: '40px'}}>Los presentes Términos y Condiciones Generales de Uso (en adelante, los "Términos y Condiciones") regulan el acceso y utilización, por parte del Usuario (conforme se define más adelante), de la página web www.tasatop.com (en adelante, "la Página Web" o "TasaTop"), así como la contratación de productos y servicios a través de la misma. La Página Web es propiedad de Maquinando Fintech S.A.C. (en adelante, La "Compañía") y es operada en cada jurisdicción por el correspondiente Operador Local (en adelante, "El Operador Local"). Cualquier persona, sea natural o jurídica que desee acceder y/o usar la Página Web deberá sujetarse a estos Términos y Condiciones, junto con todas las demás políticas y principios que rigen a TasaTop y que son incorporados al presente por referencia. En caso no acepten los términos y condiciones generales y también los particulares de carácter obligatorios y vinculantes deberán abstenerse de utilizar la página web y/o cualquier otro producto y servicio de la Compañía. El Usuario deberá leer, entender y aceptar todas las condiciones establecidas en los Términos y Condiciones y demás documentos incorporados a éstos por referencia, previo a su registro como Usuario de TasaTop.</p>
                                <li style={{listStyle: 'inside upper-latin', textAlign: 'justify', fontSize: '1.8rem'}}>Capacidad</li>
                                <p style={{textAlign: 'justify'}}>Por medio de la aceptación de los presentes Términos y Condiciones, el Usuario declara: Que ha leído y comprende lo expuesto en el presente instrumento. Que es una persona con capacidad suficiente para contratar conforme a la legislación peruana correspondiente, con el fin de dar plena validez, eficacia y utilidad práctica a todas y cada una de las estipulaciones de los presentes Términos y Condiciones. Que, en caso el Usuario sea una persona jurídica, el representante que acepta éstos términos y condiciones, cuenta con poderes y facultades suficientes para que dicha persona jurídica tenga la obligación de observar todos los términos y condiciones aquí expuestos. Que asume todas las obligaciones aquí dispuestas. El mero hecho de la navegación y/o utilización de la Página Web atribuye a quien la realice, ya sea en calidad personal o como representante de una persona jurídica, la condición de Usuario de la misma (en adelante, "el Usuario") e implica la aceptación de estos Términos y Condiciones en todas y cada una de sus partes. En consecuencia, no podrán utilizar los servicios de la Página Web, las personas que no tengan capacidad para contratar, los menores de edad y/o quienes hayan sido suspendidos o inhabilitados por la Compañía y/o el Operador Local para utilizar la Página Web.</p>
                                <li style={{listStyle: 'inside upper-latin', textAlign: 'justify', fontSize: '1.8rem'}}>Modificaciones</li>
                                <p style={{textAlign: 'justify'}}>El Usuario/Usuario Registrado (conforme se define más adelante) deberá leer atentamente y detenidamente los presentes Términos y Condiciones cada vez que acceda a la Página Web, ya que ambos pueden sufrir modificaciones sin previo aviso. La Compañía se reserva el derecho de modificar, a su sola discreción, los Términos y Condiciones en cualquier momento, o suspender, cambiar o terminar el Servicio, lo cual se publicará oportunamente en la Página Web. Toda modificación será comunicada con una antelación de 5 (cinco) días a su entrada en vigencia. En caso de no estar de acuerdo con dichas modificaciones, el Usuario deberá comunicar vía correo a la casilla contactos@tasatop.com si no acepta las mismas; en ese caso quedará disuelto el vínculo contractual y será inhabilitado como Usuario. Vencido este plazo, el Usuario acepta de manera anticipada que se considere que tácitamente acepta los nuevos Términos y Condiciones, los que regirán la relación contractual a partir de dicho momento. La Compañía se reserva el derecho de realizar, en cualquier momento y sin necesidad de preaviso, cualquier modificación o actualización de sus contenidos y servicios en general, así como de cuantos elementos integren el diseño y configuración de la Página Web.</p>
                                <li style={{listStyle: 'inside upper-latin', textAlign: 'justify', fontSize: '1.8rem'}}>Condiciones de Uso</li>
                                <ol>
                                    <li style={{listStyle: 'inside decimal', textAlign: 'justify'}}>Acceso a la Página Web</li>
                                    <p style={{textAlign: 'justify'}}>El acceso a la Página Web es gratuito, salvo en lo relativo al coste de la conexión a través de la red de telecomunicaciones suministrada por el proveedor de acceso contratado por el Usuario, que estará a su exclusivo cargo.</p>
                                    <li style={{listStyle: 'inside decimal', textAlign: 'justify'}}>Necesidad de Registro</li>
                                    <p style={{textAlign: 'justify'}}>Por regla general, para el acceso a los contenidos de la Página Web no será necesario el registro del Usuario. No obstante ello, la utilización de determinados servicios estará condicionada al registro previo del Usuario, quien deberá completar todos los campos del formulario de inscripción con datos válidos (en adelante, el "Usuario Registrado"). Quien aspire a convertirse en Usuario Registrado deberá verificar que la información que pone a disposición de TasaTop a fin de registrarse en la Página Web sea exacta, precisa y verdadera, dicha información podrá ser: Nombres, Apellidos, Documento de identidad, número de documento de identidad, fecha de nacimiento, correo electrónico, número celular; en caso sea una persona jurídica deberá ser Razón social, RUC, teléfono de contacto, cargo del usuario dentro de la persona jurídica, entre otras (en adelante, los "Datos Personales"); asimismo asumirá el compromiso de actualizar los Datos Personales cada vez que los mismos sufran modificaciones y/o cuando la Compañía lo requiera. La Compañía y/o el Operador Local podrá utilizar diversos medios para identificar a los Usuarios Registrados, pero la Compañía y/o el Operador Local no se responsabiliza por la certeza de los Datos Personales que sus Usuarios Registrados pongan a su disposición. Los Usuarios Registrados garantizan y responden, en cualquier caso, de la veracidad, exactitud, vigencia y autenticidad de los Datos Personales puestos a disposición de la Compañía y/o el Operador Local. Los Términos y Condiciones serán de aplicación tanto para los Usuarios como para los Usuarios Registrados, no obstante ello, la relación con estos últimos se regirá en forma particular por los Términos y Condiciones Particulares que les resulten aplicables.</p>
                                    <li style={{listStyle: 'inside decimal', textAlign: 'justify'}}>Obligación de mantener actualizados los Datos Personales</li>
                                    <p style={{textAlign: 'justify'}}>Los Datos Personales introducidos por todo Usuario Registrado en la Página Web, deberán ser exactos, actuales y veraces en todo momento. La Compañía y/o el Operador Local que corresponda, se reservan el derecho de solicitar algún comprobante y/o dato adicional a efectos de corroborar los Datos Personales, y de suspender temporal y/o definitivamente a aquellos Usuarios Registrados cuyos datos no hayan podido ser confirmados. La baja o inhabilitación de un Usuario Registrado implicará la baja de todas las subastas que hubiere publicado, sin que ello genere derecho a resarcimiento o indemnización alguna.</p>
                                    <li style={{listStyle: 'inside decimal', textAlign: 'justify'}}>Acceso a la cuenta personal y obligación de confidencialidad de la Clave de Seguridad</li>
                                    <p style={{textAlign: 'justify'}}>Para transformarse en Usuario Registrado, el Usuario tendrá acceso a una cuenta personal (en adelante, "Cuenta") mediante el ingreso de una cuenta de mail personal, su nombre y apellido y clave de seguridad personal elegida (en adelante, "Contraseña"). Esta Contraseña es personal e intransferible. El Usuario Registrado se obliga a mantener en estricta confidencialidad su Contraseña. El Usuario Registrado será, en todo caso, responsable por todo daño, perjuicio, lesión o detrimento que del incumplimiento de esta obligación de confidencialidad se genere por cualquier causa. La Cuenta es personal, única e intransferible, y está prohibido que un mismo Usuario Registrado registre o posea más de una Cuenta. En caso que la Compañía y/o el Operador Local que corresponda, detecte distintas Cuentas que contengan datos coincidentes o relacionados, podrá cancelarlas, suspenderlas o inhabilitarlas, a su sola discreción, siendo el mismo motivo suficiente para dar de baja al Usuario Registrado, incluso en su primera Cuenta. El Usuario Registrado será responsable por todas las operaciones efectuadas desde su Cuenta, pues el acceso a la misma está restringido al ingreso y uso de su Contraseña, de conocimiento exclusivo del Usuario y cuya confidencialidad es de su exclusiva responsabilidad. El Usuario Registrado se compromete a notificar a la Compañía y al Operador Local que corresponda según el caso, en forma inmediata y por medio idóneo, fehaciente, eficiente y eficaz, cualquier uso no autorizado de su Cuenta, así como el ingreso por terceros no autorizados a la misma al correo electrónico contactos@tasatop.com. Se encuentra prohibida la venta, cesión, transferencia o transmisión de la Cuenta bajo cualquier título, ya sea oneroso o gratuito. La Compañía y/o el Operador Local que corresponda, se reserva el derecho de rechazar cualquier solicitud de registro o de cancelar un registro previamente aceptado, cuando a su sola discreción considere que no se ha dado cumplimiento a la totalidad de las pautas establecidas en los Términos y Condiciones, sin que esté obligado a comunicar o exponer las razones de su decisión y sin que ello genere derecho a indemnización o resarcimiento alguno a favor del Usuario Registrado alcanzado por dicha decisión.</p>
                                    <li style={{listStyle: 'inside decimal', textAlign: 'justify'}}>Normas generales de utilización de la Página Web</li>
                                    <p style={{textAlign: 'justify'}}>Los servicios ofrecidos en la Página Web se dirigen exclusivamente, a personas naturales mayores edad y personas jurídicas, según corresponda. El Usuario y/o el Usuario Registrado que sea persona natural, manifiesta, garantiza y declara que tiene la edad legal para formalizar un contrato vinculante, plenamente válido y eficaz, y que toda la información de registro que presenta es exacta, veraz y actualizada. Asimismo, en caso corresponda, el representante de la persona jurídica manifiesta, garantiza y declara que cuenta con los poderes suficientes para celebrar un contrato vinculante, válido y eficaz y que todos los términos y condiciones surtirán plenos efectos frente a la persona jurídica representada; o, en todo caso, manifiesta, garantiza y declara que cuenta con la capacidad suficiente para, de acuerdo al artículo 1470 del Código Civil, lograr que la persona jurídica cuyos datos consignó en la página web, se obligue y ejecute las prestaciones correspondientes como consecuencia del servicio que brinda la Compañía o el Operador Local. La Compañía y/o el Operador Local que corresponda, se reservan el derecho a cancelar la Cuenta de aquellos Usuarios Registrados que sean personas naturales, cuya mayoría de edad resulte dudosa basándose en indicios físicos y/o contrastando con entidades públicas la información consignada, así como, en caso cuente con indicios razonables o que el representante de la persona jurídica no cuenta con poderes suficientes para obligar a su representada o que no logre obligar a la persona jurídica cuyos datos consignó en la página web. El Usuario y/o el Usuario Registrado, se obliga a utilizar la Página Web y todo su contenido y servicios conforme a lo establecido en la ley, la moral, el orden público, los presentes Términos y Condiciones, y los Términos y Condiciones Particulares que en cada caso resulten aplicables. Asimismo, se obliga a hacer un uso adecuado de los servicios y/o contenidos de la Página Web y a no emplearlos para realizar actividades ilícitas o constitutivas de delito, que atenten contra los derechos de terceros y/o que infrinjan la regulación sobre propiedad intelectual e industrial, o cualesquiera otras normas del ordenamiento jurídico que puedan resultar aplicables y, en especial, el principio de buena fe que obliga a actuar leal, correcta y honestamente tanto en los tratos preliminares, celebración y ejecución de todo contrato. Como consecuencia de lo anterior, el Usuario se obliga a no difundir, transmitir, introducir y poner a disposición de terceros, cualquier tipo de material e información (datos, contenidos, mensajes, dibujos, archivos de sonido e imagen, fotografías, software, etc.) que sean contrarios a la ley, la moral, el orden público, los presentes Términos y Condiciones, y los Términos y Condiciones Particulares que resulten aplicables.</p>
                                    <p style={{textAlign: 'justify'}}>A título meramente enunciativo, y en ningún caso limitativo, taxativo o excluyente, el Usuario y/o el Usuario Registrado, se compromete a:</p>
                                    <ol>
                                    <li style={{listStyle: 'inside lower-latin', textAlign: 'justify'}}>No introducir o difundir contenidos o propaganda de carácter racista, xenófobo o, en general, discriminatorio, pornográfico, de apología del terrorismo o que atenten, vulneren o pudieren atentar o vulnerar los derechos humanos.</li>
                                    <li style={{listStyle: 'inside lower-latin', textAlign: 'justify'}}>No introducir o difundir en la red programas de datos (virus y/o software nocivos) susceptibles de provocar daños en los sistemas informáticos de TasaTop, sus proveedores, terceros o, en general, cualquier usuario de la red Internet.</li>
                                    <li style={{listStyle: 'inside lower-latin', textAlign: 'justify'}}>No difundir, transmitir o poner a disposición de terceros cualquier tipo de información, elemento o contenido que atente contra los derechos fundamentales y las libertades públicas reconocidos constitucionalmente y en los tratados internacionales.</li>
                                    <li style={{listStyle: 'inside lower-latin', textAlign: 'justify'}}>No difundir, transmitir o poner a disposición de terceros cualquier tipo de información, elemento o contenido que constituya publicidad ilícita o desleal.</li>
                                    <li style={{listStyle: 'inside lower-latin', textAlign: 'justify'}}>No transmitir publicidad no solicitada o autorizada, material publicitario, "correo basura", "cartas en cadena", "estructuras piramidales", o cualquier otra forma de solicitación, excepto en aquellas áreas (tales como espacios comerciales) que hayan sido exclusivamente concebidas para ello mediante una comunicación expresa de la Compañía y/o del Operador Local que corresponda, comunicada debida y oportunamente en la Página Web.</li>
                                    <li style={{listStyle: 'inside lower-latin', textAlign: 'justify'}}>No introducir o difundir cualquier información y contenidos falsos, ambiguos o inexactos de forma que induzca a error a los receptores de la información.</li>
                                    <li style={{listStyle: 'inside lower-latin', textAlign: 'justify'}}>No difundir, transmitir o poner a disposición de terceros cualquier tipo de información, elemento o contenido que suponga una violación de los derechos de propiedad intelectual e industrial, patentes, marcas o copyright que correspondan a la Compañía o a terceros.</li>
                                    <li style={{listStyle: 'inside lower-latin', textAlign: 'justify'}}>No difundir, transmitir o poner a disposición de terceros cualquier tipo de información, elemento o contenido que suponga una violación del secreto de las comunicaciones y la legislación de datos de carácter personal y, en general, toda las normas jurídicas que regulen la protección y promoción del respeto a la vida privada e intimidad de las personas y sus familias.</li>
                                    <p style={{textAlign: 'justify'}}>El Usuario y/o el Usuario Registrado, se obliga a mantener indemne a la Compañía y/o al Operador Local que corresponda, ante cualquier posible reclamación, multa, pena, sanción o indemnización que pueda venir obligada a soportar como consecuencia del incumplimiento por parte del Usuario de cualquiera de las normas de utilización antes indicadas, reservándose, además, la Compañía el derecho a solicitar la indemnización por daños y perjuicios que corresponda. Asimismo, la Compañía y/o el Operador Local que corresponda, se reserva el derecho de anular la Cuenta de aquellos Usuarios Registrados que hagan un uso inapropiado de la Página Web o no respeten las observaciones y prohibiciones previstas por estos Términos y Condiciones, y los Términos y Condiciones Particulares que resulten aplicables en cada caso.</p>
                                    </ol>

                                    <li style={{listStyle: 'inside decimal', textAlign: 'justify'}}>Consideraciones de las subastas</li>
                                    <p style={{textAlign: 'justify'}}>La adjudicación de la oferta al Usuario no tiene carácter de vinculación ni obligación de concreción del producto o depósito de ahorro ofertado.</p>
                                    <p style={{textAlign: 'justify'}}>El Usuario tiene dos (02) días hábiles, contados desde la adjudicación de la oferta, para poder contactarse con la entidad financiera ganadora de la subasta – cuyos datos serán proporcionados por TasaTop - y hacer efectivo el depósito de ahorro en las condiciones ofertadas. Vencido el plazo de dos (02) días hábiles, las condiciones ofertadas no serán exigiblesa a tal entidad financiera. Sin perjuicio de lo señalado ello, dicha entidad, de manera unilateral y discrecional, podrá prorrogar el plazo antes indicado.</p>
                                    <p style={{textAlign: 'justify'}}>El Usuario declara conocer y acepta que, luego de adjudiciación de la oferta por exigencia regulatoria deberán someterse a la evaluación de entidad financiera ganadora a efecto de determinar la viabilidad legal de la contratación en cumplimiento de las exigencias regulatorias de la Superintendencia de Banca Seguros y AFP´s pero respetando, en las condiciones ofertadas en la subasta.</p>
                                    <p style={{textAlign: 'justify'}}>En ese sentido, el Usuario declara conocer y acepta que la entidad financiera ganadora de la subasta podrá dejar sin efecto la adjudicación de la oferta si el Usuario, no cumple con los exigencias regulatorias para contratar, tales como, calificación negativa en el sistema financiero, es sujeto de investigación por comisión de delitos de lavado de activos, financiamiento del terrorismo o haya sido sentenciado por éstos, entre otros. Siendo así, la entidad financiera, sin responsabilidad, no se encontrará obligada a contratar con elUsuario.</p>
                                    <li style={{listStyle: 'inside decimal', textAlign: 'justify'}}>Responsabilidad de TasaTop y/o el Operador Local que corresponda</li>
                                    <p style={{textAlign: 'justify'}}>Por cuanto TasaTop y/o el Operador Local que corresponda, sólo pone a disposición de los Usuarios un espacio virtual que permite a los Usuarios Registrados poner sus Subastas a disposición de las entidades financieras participantes mediante internet:</p>
                                    <ol>
                                    <li style={{listStyle: 'inside lower-latin', textAlign: 'justify'}}>La Compañía y/o el Operador Local que corresponda, no asume ninguna responsabilidad sobre el contenido o información del Usuario Registrado, ni garantiza que la información publicada contenida en la Página Web sea precisa ni completa. Por lo tanto, cada Usuario Registrado será responsable de confirmar que la información publicada en la Página Web sea precisa y completa antes de tomar alguna decisión relacionada con cualquier servicio o contenido descrito en la misma.</li>
                                    <li style={{listStyle: 'inside lower-latin', textAlign: 'justify'}}>El acceso del Usuario / Usuario Registrado a la Página Web no implica para la Compañía y/o el Operador Local que corresponda, la obligación de informar, controlar o, actuación alguna referente a la ausencia o presencia de virus, gusanos o cualquier otro elemento informático dañino. Los Usuarios no podrán imputarle responsabilidad alguna a la Compañía y/o al Operador Local que corresponda, ni exigir indemnización bajo ningún concepto, por los perjuicios resultantes de dificultades técnicas o fallas en los sistemas o en internet.</li>
                                    <li style={{listStyle: 'inside lower-latin', textAlign: 'justify'}}>La Compañía y/o el Operador Local que corresponda, no garantiza el acceso y uso continuado e ininterrumpido de la Página Web. La Página Web puede eventualmente no estar disponible debido a dificultades técnicas o fallas de internet, o por cualquier otra circunstancia ajena y no imputable a la Compañía y/o al Operador Local que corresponda; en tales casos se procurará restablecerlo con la mayor celeridad posible sin que por ello pueda imputársele algún tipo de responsabilidad. La Compañía y/o el Operador Local que corresponda, no serán responsables por ningún error u omisión contenidos en la Página Web.</li>
                                    <li style={{listStyle: 'inside lower-latin', textAlign: 'justify'}}>Corresponde al Usuario, en todo caso, la disponibilidad de herramientas adecuadas para la detección y desinfección de programas informáticos dañinos.</li>
                                    <li style={{listStyle: 'inside lower-latin', textAlign: 'justify'}}>La Compañía y/o el Operador Local que corresponda, no se responsabilizan de los daños o perjuicios de cualquier tipo producidos en el Usuario a causa de fallos o desconexiones en las redes de telecomunicaciones que produzcan la suspensión, cancelación o interrupción del servicio de la Página Web durante la prestación del mismo o con carácter previo.</li>
                                    <li style={{listStyle: 'inside lower-latin', textAlign: 'justify'}}>La Compañía ni el Operador Local, en caso corresponda, no serán responsables por causas que no son directamente imputables a éstos.</li>
                                    </ol>
                                    <li style={{listStyle: 'inside decimal', textAlign: 'justify'}}>Contenidos y servicios enlazados a través de la Página Web</li>
                                    <p style={{textAlign: 'justify'}}>El servicio de acceso a la Página Web puede incluir dispositivos técnicos de enlace, directorios e incluso instrumentos de búsqueda que permitan al Usuario acceder a otras páginas y portales de Internet (en adelante, "Sitios Enlazados"). En estos casos, la Compañía y/o el Operador Local que corresponda, sólo serán responsables de los contenidos y servicios suministrados en los Sitios Enlazados en la medida en que tengan conocimiento efectivo de la ilicitud y no hayan desactivado el enlace con la diligencia debida. En el supuesto que el Usuario considere que existe un Sitio Enlazado con contenidos ilícitos o inadecuados podrá comunicárselo a la Compañía y/o el Operador Local que corresponda, sin que en ningún caso esta comunicación conlleve la obligación de la Compañía y/o del Operador Local que corresponda, de retirar el correspondiente enlace. En ningún caso, la existencia de Sitios Enlazados debe presuponer la formalización de acuerdos ni asociación con los responsables o titulares de los mismos, ni la recomendación, promoción o identificación de TasaTop y/o del Operador Local que corresponda, con las manifestaciones, contenidos o servicios proveídos por dichos sitios. La Compañía y/o el Operador Local que corresponda, no conocen los contenidos y servicios de los Sitios Enlazados y, por tanto, no se hacen responsables por los daños producidos por la ilicitud, calidad, desactualización, indisponibilidad, error e inutilidad de los contenidos y/o servicios de los Sitios Enlazados ni por cualquier otro daño que no sea directamente imputable a la Compañía y/o al Operador Local que corresponda.</p>
                                    <li style={{listStyle: 'inside decimal', textAlign: 'justify'}}>Propiedad intelectual e industrial</li>
                                    <p style={{textAlign: 'justify'}}>Todos los contenidos de la Página Web, entendiendo por éstos, a título meramente enunciativo y no taxativo, los textos, fotografías, gráficos, imágenes, iconos, tecnología, software, links y demás contenidos audiovisuales o sonoros, así como su diseño gráfico y códigos fuente, son propiedad intelectual de la Compañía o de terceros, sin que puedan entenderse cedidos al Usuario ninguno de los derechos de explotación reconocidos por la normativa vigente en materia de propiedad intelectual sobre los mismos. Asimismo, las marcas, nombres comerciales o signos distintivos son de propiedad de la Compañía o terceros, sin que pueda entenderse que el acceso a la Página Web atribuye algún derecho sobre los mismos. Cualquier intromisión, tentativa o actividad violatoria o contraria a las leyes sobre derecho de propiedad intelectual y/o a las prohibiciones estipuladas en este contrato harán pasible a su responsable de las acciones legales pertinentes, y a las sanciones previstas por este acuerdo, así como lo hará responsable de indemnizar los daños ocasionados.</p>
                                    <li style={{listStyle: 'inside decimal', textAlign: 'justify'}}>Sanciones</li>
                                    <p style={{textAlign: 'justify'}}>Sin perjuicio de otras medidas, la Compañía y/o el Operador Local que corresponda, podrán advertir, suspender en forma temporal o inhabilitar definitivamente la cuenta de un Usuario Registrado, iniciar las acciones que estimen pertinentes y/o suspender la prestación de sus servicios, si;</p>
                                    <ol>
                                    <li style={{listStyle: 'inside lower-latin', textAlign: 'justify'}}>se quebranta o incumple alguna ley, o cualquiera de las estipulaciones de los Términos y Condiciones, demás políticas de TasaTop</li>
                                    <li style={{listStyle: 'inside lower-latin', textAlign: 'justify'}}>incumple sus obligaciones como Usuario Registrado;</li>
                                    <li style={{listStyle: 'inside lower-latin', textAlign: 'justify'}}>no pudiere verificarse la identidad del Usuario Registrado o cualquier información proporcionada por el mismo fuere errónea; o,</li>
                                    <li style={{listStyle: 'inside lower-latin', textAlign: 'justify'}}>si se incurriera a criterio de TasaTop, en conductas o actos dolosos o fraudulentos.</li>
                                    </ol>
                                    <li style={{listStyle: 'inside decimal', textAlign: 'justify'}}>Indemnidad</li>
                                    <p style={{textAlign: 'justify'}}>El Usuario indemnizará y mantendrá indemnes a la Compañía y/o al Operador Local que corresponda, sus filiales, empresas controladas y/o controlantes, directores administradores, representantes y empleados, por cualquier reclamo o demanda de otros Usuarios o de terceros por sus actividades en la Página Web o por el incumplimiento de los Términos y Condiciones, de las demás políticas que se entienden incorporadas al presente instrumento, incluyendo los honorarios de abogados en una cantidad razonable.</p>
                                </ol>

                                <li style={{listStyle: 'inside upper-latin', textAlign: 'justify', fontSize: '1.8rem'}}>Nulidad e ineficacia de las cláusulas</li>
                                <p style={{textAlign: 'justify'}}>Si cualquier cláusula incluida en los Términos y Condiciones fuese declarada total o parcialmente, nula o ineficaz en alguna de las jurisdicciones en las que la Compañía tiene presencia, tal nulidad o ineficacia tan sólo afectará a dicha disposición o a la parte de la misma que resulte nula o ineficaz, subsistiendo los Términos y Condiciones en todo lo demás, considerándose tal disposición total o parcialmente no incluida o aplicable en aquella jurisdicción.</p>
                                <li style={{listStyle: 'inside upper-latin', textAlign: 'justify', fontSize: '1.8rem'}}>Privacidad de la información</li>
                                <p style={{textAlign: 'justify'}}>Para utilizar los Servicios ofrecidos por TasaTop y/o por el Operador Local que corresponda, los Usuarios que deseen convertirse en Usuarios Registrados, se obligan a facilitar determinados datos de carácter personal prestando su consentimiento para el uso del website. Su información personal se procesa y almacena en servidores o medios magnéticos que mantienen altos estándares de seguridad y protección tanto física como tecnológica.</p>
                                <li style={{listStyle: 'inside upper-latin', textAlign: 'justify', fontSize: '1.8rem'}}>Alcance de los servicios de TasaTop</li>
                                <p style={{textAlign: 'justify'}}>Este acuerdo no crea ningún contrato de sociedad, de mandato, de franquicia, o relación laboral entre el Usuario y la Compañía y/o el Operador Local. El Usuario reconoce y acepta que la Compañía y/o el Operador Local que corresponda, no son parte en ninguna operación, ni tienen control alguno sobre la calidad, seguridad o legalidad de los proyectos publicados y la veracidad o exactitud de sus características. La Compañía y/o el Operador Local que corresponda, no garantizan la veracidad de la publicidad de terceros que aparezca en el sitio y no será responsable por la correspondencia y/o contratos que el Usuario celebre con dichos terceros o con otros Usuarios.</p>
                                <li style={{listStyle: 'inside upper-latin', textAlign: 'justify', fontSize: '1.8rem'}}>Preguntas frecuentes</li>
                                <p style={{textAlign: 'justify'}}>Las respuestas a las preguntas frecuentes no hacen referencia a todas las consecuencias legales, impositivas, cambiarías posibles relacionadas. Las respuestas a las preguntas frecuentes no implican en ningún caso asesoramiento legal o impositivo por parte de TasaTop y/o la Compañía y/o el Operador Local. Estos Términos y Condiciones así como los Términos y Condiciones Particulares que resulten aplicables según el caso, prevalecerán siempre sobre el contenido de la información relativa a Preguntas Frecuentes.</p>
                                <li style={{listStyle: 'inside upper-latin', textAlign: 'justify', fontSize: '1.8rem'}}>Legislación aplicable y jurisdicción competente</li>
                                <p style={{textAlign: 'justify'}}>Estos Términos y Condiciones se regirán o interpretarán conforme a la legislación en los tribunales del Perú. La Compañía y/o el Operador Local que corresponda, y el Usuario podrán someter cualquier controversia que pudiera suscitarse de la prestación de los productos o servicios objeto de éstos Términos y Condiciones, a los Juzgados, Tribunales o cualquier otra autoridad pública, estatal o federal del domicilio de la Compañía y/o del Operador Local que corresponda, a menos que legalmente se establezca lo contrario.</p>

                                <li style={{listStyle: 'inside upper-latin', textAlign: 'justify', fontSize: '1.8rem'}}>Tratamiento y Datos Personales</li>
                                <p style={{textAlign: 'justify'}}>El Usuario / Usuario Registrado que cumpla con los requisitos mencionados en a lo largo de los Términos y Condiciones declara, reconoce y/o autoriza de forma expresa:</p>
                                <ol>
                                    <li style={{listStyle: 'inside decimal', textAlign: 'justify'}}>Que otorga su consentimiento expreso para que Maquinando Fintech S.A.C. pueda tratar sus datos personales para el cumplimiento del servicio brindado y fines expresados en este documento, así como para todo lo que indique los presentes términos y condiciones, de acuerdo a lo establecido en el presente documento. Dicho consentimiento se otorga conforme a la Ley de Protección de Datos Personales, su Reglamento y demás normas conexas.</li>
                                    <li style={{listStyle: 'inside decimal', textAlign: 'justify'}}>Que los datos personales proporcionados, así como cualquier otro dato que pudiera facilitarse a lo largo de la relación contractual, sean incluidos en un Banco de Datos, automatizado o no, cuyo titular y responsable es Maquinando Fintech S.A.C. con domicilio legal en Calle Loma de los Suspiros 332 oficina 601 distrito de Surco del departamento de Lima, Perú , única destinataria de los datos, con la finalidad de llevar a cabo la relación contractual, la gestión propia de la actividad, el mantenimiento, desarrollo y control de la relación contractual.</li>
                                    <li style={{listStyle: 'inside decimal', textAlign: 'justify'}}>Que Maquinando Fintech S.A.C. validará de forma expresa los datos del Usuario / Usuario Registrado a través de llamadas, correos, mensajes así como la creación de subastas en salvaguarda del Usuario /Usuario Registrado así como de las entidades financieras participantes.</li>
                                    <li style={{listStyle: 'inside decimal', textAlign: 'justify'}}>La grabación de las llamadas telefónicas que realice a los números de teléfono de contacto de Maquinando Fintech S.A.C.a los efectos de control de calidad de las llamadas y gestión de las incidencias y de las reclamaciones.</li>                                    
                                </ol>
                                <p style={{textAlign: 'justify'}}>Todos los datos recabados, así como los anteriores tratamientos, son imprescindibles para el establecimiento y desarrollo de la relación contractual. El Usuario / Usuario Registrado, en el caso de que se produzca alguna variación en los datos facilitados a Maquinando Fintech S.A.C. para su tratamiento de conformidad con lo previsto en la presente cláusula, lo notificará a ésta para que por parte de Maquinando Fintech S.A.C.se proceda a dicha modificación.</p>
                                <p style={{textAlign: 'justify'}}>El Usuario / Usuario Registrado, en atención a lo establecido en la Ley de Protección de Datos Personales y su Reglamento otorga de manera expresa, libre, previa e informada su consentimiento a favor de Maquinando Fintech, S.A.C. para que, éste último pueda utilizar y tratar todos los datos personales brindados con la estricta finalidad de:</p>
                                <ol>
                                    <li style={{listStyle: 'inside decimal', textAlign: 'justify'}}>Ser incluido en su banco de datos para que Maquinando Fintech, S.A.C. realice el servicio contratado, lo cual incluye la transferencia de sus datos personales a las entidades financieras que hayan ganado las subastas, a las compañías que brinden tratamiento de datos personales por encargo a nivel nacional o internacional, a servidores que tienen su domicilio en EE.UU. (Virginia del Norte, Ohio, California del Norte, Oregón). Asia (Bombay, Corea - Seúl, Singapur - Singapur, Australia - Sídney, Japón - Tokio, China - Pekín). Canadá. Europa (Alemania - Fráncfort, Irlanda, Inglaterra - Londres). América del Sur (Brasil - Sao Paulo). Se deja constancia que, luego de finalizado el vínculo contractual, el Usuario / Usuario Registrado otorga su consentimiento para que Maquinando Fintech, S.A.C. siga tratando sus datos personales hasta que éste, de manera expresa revoque dicho consentimiento.</li>
                                    <li style={{listStyle: 'inside decimal', textAlign: 'justify'}}>La realización de segmentaciones con la finalidad de utilizar los datos que obran en los ficheros de la compañía, para la realización de estudios de marketing, adaptación de la publicidad en función de las segmentaciones realizadas, análisis estadísticos, elaboración de perfil de cliente, así como la utilización de dicha información para la realización de las campañas publicitarias y comerciales que se indican en el punto siguiente, lo cual incluye el consentimiento para que Maquinando Fintech, S.A.C. realice la transferencia de los datos personales, en caso sea necesaria.</li>
                                    <li style={{listStyle: 'inside decimal', textAlign: 'justify'}}>Que le remita información publicitaria y comercial, incluso por medios electrónicos, sobre productos o servicios de Maquinando Fintech, S.A.C. o relacionados con los sistemas de alimentación y acabado para procesos de impresión, personalización y mailing de tarjetas y afines, incluso adaptada a sus circunstancias personales. Se deja constancia que, para el cumplimiento de éste fin, Maquinando Fintech, S.A.C. podrá transferir los datos personales a persona distinta o por encargo, en caso sea necesario.</li>                           
                                </ol>
                                <p style={{textAlign: 'justify'}}>Una vez finalizada la relación contractual entre el Usuario / Usuario Registrado y Maquinando Fintech, S.A.C., para que éste último pueda seguir haciendo uso de sus datos personales para fines comerciales y publicitarios, en los términos indicados en la presente cláusula, hasta que el CLIENTE no revoque el consentimiento dado o, en cualquier caso, una vez transcurra un año desde la extinción de pleno efecto de la relación contractual.</p>
                                <p style={{textAlign: 'justify'}}>La oposición a los tratamientos indicados en los puntos 2 y 3 inmediatamente anteriores, no conllevará ningún perjuicio para el Usuario / Usuario Registrado. En caso de no desear autorizar dichos tratamientos, el Usuario / Usuario Registrado podrá manifestar su oposición por escrito de forma gratuita por cualquiera de los medios mencionados en el párrafo siguiente. En caso de contratación presencial deberá manifestar en el momento de la firma del contrato su deseo de no autorizar dichos tratamientos con finalidad publicitaria. En cualquier caso, lo podrá realizar a través del correo electrónico que se indica en el último párrafo de la presente estipulación.</p>
                                <p style={{textAlign: 'justify'}}>El Usuario / Usuario Registrado podrá ejercitar los derechos de acceso, rectificación, cancelación y oposición accediendo por el portal de la página web www.tasatop.com, o bien dirigiendo su solicitud mediante el correo electrónico contactos@tasatop.com.</p>
                                <li style={{listStyle: 'inside upper-latin', textAlign: 'justify', fontSize: '1.8rem'}}>Flujograma de contacto y validación de los datos por Tasatop</li>
                                <p style={{textAlign: 'justify'}}>Maquinando Fintech se contactará vía telefónica con el Usuario / Usuario Registrado hasta en 03 oportunidades según los siguientes pasos del proceso de experiencia.</p>
                                <ol style={{marginBottom: '50px'}}>
                                    <li style={{listStyle: 'inside decimal', textAlign: 'justify'}}>Inscripción en TasaTop.</li>
                                    <li style={{listStyle: 'inside decimal', textAlign: 'justify'}}>Inscripción de la subasta.</li>
                                    <li style={{listStyle: 'inside decimal', textAlign: 'justify'}}>Recordación de subasta ganada.</li>                           
                                </ol>





                            </ol>

                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    {/* <!--======= End Blog =======--> */}
</div>
        </React.Fragment>
    )
}  

export default Blog21;